SELECT * FROM SCOTT.EMP WHERE ENAME NOT LIKE  '%';

SELECT * FROM SCOTT.EMP WHERE ENAME LIKE '%';

SELECT * FROM SCOTT.EMP WHERE ENAME LIKE 'S%T';

SELECT * FROM SCOTT.EMP EMP 
WHERE EXISTS 
(
SELECT DEP.DEPTNO FROM DEPT DEP 
WHERE DEP.DEPTNO IN (30,60,90)
AND EMP.DEPTNO = DEP.DEPTNO
);

select * from scott.emp where not deptno between 20 and 40